In [1]:
from cobra import Model, Reaction, Metabolite

In [3]:
# Create model
model = Model("toy_model")

In [5]:
# Define metabolites
glc = Metabolite("glc", compartment="e")
o2 = Metabolite("o2", compartment="e")
A = Metabolite("A", compartment="c")
B = Metabolite("B", compartment="c")
C = Metabolite("C", compartment="c")

In [6]:
# Define reactions
# Exchange reactions
Ex_glc = Reaction("Ex_glc")
Ex_glc.add_metabolites({glc: -1})
Ex_glc.lower_bound = -10  # uptake allowed
Ex_glc.upper_bound = 0

Ex_o2 = Reaction("Ex_o2")
Ex_o2.add_metabolites({o2: -1})
Ex_o2.lower_bound = -10  # uptake allowed
Ex_o2.upper_bound = 0

# Internal reactions
R1 = Reaction("R1")
R1.add_metabolites({glc: -1, A: 1})

R2 = Reaction("R2")
R2.add_metabolites({A: -1, C: 1})
R2.lower_bound = 0
R2.upper_bound = 1000

R3 = Reaction("R3")
R3.add_metabolites({C: -1})

R4 = Reaction("R4")
R4.add_metabolites({A: -1, o2: -1, B: 1})

R5 = Reaction("R5")
R5.add_metabolites({B: -1})

# Add reactions to model
model.add_reactions([Ex_glc, Ex_o2, R1, R2, R3, R4, R5])

In [ ]:
# Set Objective: Maximize Production of C

In [9]:
model.objective = "R2"

# Simulate Anaerobic Conditions

In [14]:
model.reactions.Ex_o2.lower_bound = 0  # no oxygen uptake
solution_anaerobic = model.optimize()
print(f"Anaerobic C production: {solution_anaerobic.fluxes['R2']}")

Anaerobic C production: 10.0

# Simulate Aerobic Conditions

In [13]:
model.reactions.Ex_o2.lower_bound = -10  # oxygen available
solution_aerobic = model.optimize()
print(f"Aerobic C production: {solution_aerobic.fluxes['R2']}")

Aerobic C production: 10.0

1. If this pathway (R4 & R5) doesn't contribute additional flux toward making C, then adding oxygen won't help.

2. R2 (A → C) works independently of oxygen—so maximizing C only depends on how much A is available, not on whether oxygen is present.

In [15]:
model.summary()